
services:
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - my_network
    init : true

  nginx:
    container_name: nginx-container
    build: ./requirements/nginx/
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - "443:443"
    init : true

  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - my_network
    init : true


networks:
  my_network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/meharit/data/mariadb
  
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/meharit/data/wordpress