#!/bin/sh

service mariadb start

sleep 5

mariadb -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS mydatabase;"

mariadb -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';"

mariadb -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON mydatabase.* TO '$MYSQL_USER'@'%';"

mariadb -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

mysqladmin -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD  shutdown

mysqld